-- This is the flat file that will be used to generate tte_contract_management_2026.sqlx

config {
    type: "table",
    tags: ["tte"],
    bigquery: {
        partitionBy: "DATE(application_created_at)",
        clusterBy: ["lead_provider_name", "course_name", "application_status"]
    }
}

SELECT
    -- Application
    application_id,
    application_ecf_id,
    application_status,
    application_created_at,
    application_updated_at,

    -- Funding
    eligible_for_funding,
    funded_place,
    funding_choice,
    funding_eligiblity_status_code,
    targeted_support_funding_eligibility,

    -- Provider
    lead_provider_name,
    lead_provider_ecf_id,

    -- Course
    course_name,
    course_identifier,
    course_short_code,
    course_group,

    -- Cohort
    cohort_identifier,
    cohort_start_year,

    -- Schedule
    schedule_name,
    schedule_training_starts_at,
    schedule_training_ends_at,

    -- Institution
    institution_name,
    institutionable_type,
    region,

    -- School
    la_name,
    phase_name,
    establishment_type_name,
    high_pupil_premium,

    -- Declaration
    declaration_type,
    declaration_state,
    declaration_date,

    -- Participant outcome
    participant_outcome_state_result,
    participant_outcome_completion_date,

    -- Flags
    eligible_for_funding = TRUE
    AND application_status IN ('pending', 'accepted') AS flag_eligible_pending_or_accepted,

    application_status = 'accepted'
    AND funded_place = TRUE AS flag_accepted_funded,

    funded_place = TRUE
    AND declaration_type = 'started'
    AND declaration_state IN ('submitted', 'eligible', 'payable', 'paid')   AS flag_started_declaration_paid

FROM ${ref('tte_enrolments')}
WHERE cohort_identifier = '2026-July'